config/routes.rb
Rails.application.routes.draw do
  resources :todos, only: [:index, :create, :new] do
    resource :completion, only: [:create]
  end

  resource :session, only: [:new, :create]

  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  def completed?
    completed_at?
  end
end

app/models/user.rb
class User
  def initialize(email)
    @email = email
  end

  def todos
    Todo.where(email: @email)
  end

  def signed_in?
    @email.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate
    if !signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user.signed_in?
  end

  def sign_in_as(email)
    session[:current_email] = email
  end

  def current_user
    User.new(session[:current_email])
  end
end

app/controllers/completions_controller.rb
class CompletionsController < ApplicationController
  def create
    @todo = current_user.todos.find(params[:todo_id]).touch :completed_at
    redirect_to root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    sign_in_as params[:session][:email]
    redirect_to root_path
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate

  def index
    @todos = current_user.todos
  end

  def new
    @todo = Todo.new
  end

  def create
    current_user.todos.create(todo_params)
    redirect_to root_path
  end

  private

  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <h1>Todos</h1>

    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<%= link_to "Add a new todo", new_todo_path %>

<ul class="todos">
<% @todos.each do |todo| %>
  <li class="<%= "completed" if todo.completed? %>">
    <%= todo.title %>
    <% unless todo.completed? %>
      |
      <%= button_to "Mark as complete", todo_completion_path(todo) %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.submit %>
<% end %>